[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  name = "github.com/montanaflynn/stats"
  version = "0.5.0"

[prune]
  go-tests = true
  unused-packages = true
