[[constraint]]
  name = "github.com/Knetic/govaluate"
  version = "3.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[prune]
  go-tests = true
  unused-packages = true
